vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        vinyls:
            uri_prefix: '%vinyl_attachments%'
            upload_destination: '%kernel.project_dir%/public%vinyl_attachments%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
